//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greedy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Greedy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000000
        ///2118570393487230451686356948210
        ///0000980590000490450000030000270
        ///0783968620894734490574246539580
        ///0930000070000100000280000100000
        ///0934994398330930626260556110410
        ///0000490000110970870000150480440
        ///0520860820736790748639390860420
        ///0880540220000000050000000280770
        ///0290380420341432340128520968210
        ///0980470620490000390380000000340
        ///0520750599750231360682383968580
        ///0910490000010000420000200000390
        ///0590122421230256873589995930370
        ///0690000000580210910000000860660
        ///01807273609301301 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maze_1 {
            get {
                return ResourceManager.GetString("maze_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000000
        ///8548066369033108825887037866050
        ///0700060009000700080009000004010
        ///0763028609881427159708681501080
        ///0007000400000800000900000408010
        ///0381220941020804982407729901030
        ///0600000009020604000004000005080
        ///0905991469390408417602630618480
        ///0101000000000200000200090006000
        ///0509053909982102889602095305040
        ///0801000908000001000001000108010
        ///0205965503012707045305021503910
        ///0700090005000307080605080008000
        ///0801190693528804580148056106890
        ///0904000500000000000004000407000
        ///06760398034308389 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maze_2 {
            get {
                return ResourceManager.GetString("maze_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000000
        ///1307517608296135048801654539070
        ///0105000606000000040508000008080
        ///0306067997015605260801958308080
        ///0601070700010201000300000805070
        ///0342080221070841065604756806060
        ///0000010001070000050008000009090
        ///0706760179036308370694050532060
        ///0506000700000908000000020203040
        ///0342019364057602013805990207030
        ///0000000001050008040301000100070
        ///0368120941060767020906554408490
        ///0300090600020300080400070007000
        ///0305070328190344330591290388720
        ///0304040000000800000500000900070
        ///06070909042564070 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maze_3 {
            get {
                return ResourceManager.GetString("maze_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11111111111111111
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///10203040506070809
        ///|
        ///goal / energy
        ///9 733
        ///|
        ///position
        ///16 0
        ///|
        ///0 9
        ///2 9
        ///4 9
        ///6 9
        ///8 9
        ///10 9
        ///12 9
        ///14 9
        ///16 9.
        /// </summary>
        internal static string maze_4 {
            get {
                return ResourceManager.GetString("maze_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111
        ///111
        ///111|
        ///goal / energy
        ///2 100
        ///|
        ///position
        ///0 0
        ///|
        ///2 2.
        /// </summary>
        internal static string maze_no_chests {
            get {
                return ResourceManager.GetString("maze_no_chests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111
        ///111
        ///111|
        ///goal / energy
        ///1 2
        ///|
        ///position
        ///0 0
        ///|
        ///2 2.
        /// </summary>
        internal static string maze_no_energy {
            get {
                return ResourceManager.GetString("maze_no_energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00000000000000000000000000000000000000000
        ///54442302672704758744239609897969015531740
        ///09000500080306060000000408000900010000060
        ///06069541140946040435077702010784880587420
        ///00020000000000090008020004010000000900000
        ///05250367140249010972079807032682490836530
        ///09000005070002050600000802000200040000050
        ///07286504090294070789348709077602160266210
        ///00000606080700080000070003080004000004000
        ///04568207080233010526082989038301881821060
        ///02000000010305030002000000000900000004080
        ///094449124308077508160258012807027101270 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string maze_time_limit {
            get {
                return ResourceManager.GetString("maze_time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27764793689153674318
        ///98653556955267961666
        ///64341647214954141238
        ///34324857417865255356
        ///27481572755837432213
        ///26424631369877759418
        ///13185859184423454254
        ///36916626983713285576
        ///24942574321897544128
        ///69925639261848397592
        ///97388584775549924885
        ///37372341467811887241
        ///89252555915874925665
        ///17929643115247636756
        ///89141827264168119155
        ///22595459766719727511
        ///57247565763631564297
        ///42161616184515151121
        ///79223151527564636631
        ///41492858916399951831
        ///|
        ///goal / energy
        ///6 118
        ///|
        ///position
        ///10 10
        ///|
        ///3 6
        ///14 4
        ///0 13
        ///0 5
        ///19 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string no_walls_1 {
            get {
                return ResourceManager.GetString("no_walls_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 574
        ///616
        ///224
        ///|
        ///goal / energy
        ///3 20
        ///|
        ///position
        ///1 1
        ///|
        ///0 2
        ///2 0
        ///2 2.
        /// </summary>
        internal static string no_walls_2 {
            get {
                return ResourceManager.GetString("no_walls_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2772269186
        ///1498765121
        ///8179222337
        ///4755644548
        ///9954415564
        ///1976521899
        ///4671238533
        ///2964196362
        ///6769749895
        ///4555442421
        ///|
        ///goal / energy
        ///10 116
        ///|
        ///position
        ///5 5
        ///|
        ///2 6
        ///9 2
        ///8 4
        ///6 0
        ///5 6
        ///0 5
        ///6 2
        ///9 4
        ///2 5
        ///9 1.
        /// </summary>
        internal static string no_walls_3 {
            get {
                return ResourceManager.GetString("no_walls_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9877391841963554723296877912538568445451
        ///3467474958266373119399413415128472961131
        ///6166129322354223154168941894412978784792
        ///4848849517656257226326819485438363775166
        ///8537574549621698949455188393573269573263
        ///1314773939721224459371177451235876434612
        ///1916922582482451347322714944789748371485
        ///3131967424118898292187892644289853919727
        ///3933898684513866338333344256889584894523
        ///7867396664868859699743795138172816547615
        ///5995136988446585163268692163322984253392
        ///4392382679313897313974776452343872838464
        ///89538171 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string no_walls_time_limit {
            get {
                return ResourceManager.GetString("no_walls_time_limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110000
        ///110000
        ///110001
        ///111111
        ///110001
        ///110000
        ///110000
        ///|
        ///goal / energy
        ///7 12
        ///|
        ///position
        ///3 3
        ///|
        ///0 0
        ///0 1
        ///0 2
        ///0 3
        ///0 4
        ///0 5
        ///0 6
        ///5 2
        ///4 3
        ///5 3
        ///5 4.
        /// </summary>
        internal static string not_greedy_maze_1 {
            get {
                return ResourceManager.GetString("not_greedy_maze_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3111
        ///|
        ///goal / energy
        ///2 6
        ///|
        ///position
        ///1 0
        ///|
        ///0 0
        ///3 0.
        /// </summary>
        internal static string not_greedy_no_walls_1 {
            get {
                return ResourceManager.GetString("not_greedy_no_walls_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1911
        ///|
        ///goal / energy
        ///2 10
        ///|
        ///position
        ///2 0
        ///|
        ///0 0
        ///1 0
        ///3 0.
        /// </summary>
        internal static string not_greedy_no_walls_2 {
            get {
                return ResourceManager.GetString("not_greedy_no_walls_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111111191119999000019111111111
        ///113111119119999000011911111131
        ///139311111919999000011191111393
        ///113119111919999111111191191131
        ///139311111919999000011191111393
        ///113111119119999000011911111131
        ///111111191119999000019111111111
        ///|
        ///goal / energy
        ///3 84
        ///|
        ///position
        ///15 3
        ///|
        ///2 2
        ///2 4
        ///5 3
        ///28 2
        ///28 4.
        /// </summary>
        internal static string not_greedy_no_walls_3 {
            get {
                return ResourceManager.GetString("not_greedy_no_walls_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99999999199999999
        ///99999991119999999
        ///99999912121999999
        ///99999123132199999
        ///99991234143219999
        ///99912345154321999
        ///99123456165432199
        ///91234567176543219
        ///12345678187654321
        ///91234567876543219
        ///99123456765432199
        ///99912345654321999
        ///99991234543219999
        ///99999123432199999
        ///99999912321999999
        ///99999991219999999
        ///99999999199999999
        ///|
        ///goal / energy
        ///2 39
        ///|
        ///position
        ///8 8
        ///|
        ///7 15
        ///9 15
        ///8 0.
        /// </summary>
        internal static string not_greedy_no_walls_4 {
            get {
                return ResourceManager.GetString("not_greedy_no_walls_4", resourceCulture);
            }
        }
    }
}
